#!/usr/bin/env node
/**
 * Scans apps/client/public/assets/sprites and derives a sprite manifest.
 *
 * Layout conventions baked into the source art:
 *   heroes/<class>/<dir>-<action>.png  single row, square frames -> frames = width / height
 *   monsters/<id>/<action>.png         4 rows (down,up,left,right), square frames
 *                                      -> frameSize = height / 4, frames = width / frameSize
 *   skills/<name>.png                  single 128x128 icon
 *
 * Re-run with `pnpm assets` after dropping new art in.
 */
import { readdirSync, readFileSync, writeFileSync, statSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spriteRoot = join(root, "apps/client/public/assets/sprites");

/** Reads width/height straight out of the PNG IHDR chunk — no image library needed. */
function pngSize(file) {
  const buf = readFileSync(file);
  if (buf.readUInt32BE(0) !== 0x89504e47) throw new Error(`not a PNG: ${file}`);
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

const dirs = (p) =>
  existsSync(p) ? readdirSync(p).filter((d) => statSync(join(p, d)).isDirectory()).sort() : [];
const pngs = (p) =>
  existsSync(p) ? readdirSync(p).filter((f) => f.endsWith(".png")).sort() : [];

const manifest = { heroes: {}, monsters: {}, skills: [] };

for (const cls of dirs(join(spriteRoot, "heroes"))) {
  const anims = {};
  let frameWidth = 0;
  let frameHeight = 0;
  for (const file of pngs(join(spriteRoot, "heroes", cls))) {
    const { width, height } = pngSize(join(spriteRoot, "heroes", cls, file));
    if (width % height !== 0) throw new Error(`hero sheet not a whole number of square frames: ${cls}/${file}`);
    frameWidth = frameHeight = height;
    anims[basename(file, ".png")] = {
      file: `sprites/heroes/${cls}/${file}`,
      frames: width / height,
    };
  }
  if (Object.keys(anims).length) manifest.heroes[cls] = { frameWidth, frameHeight, anims };
}

for (const id of dirs(join(spriteRoot, "monsters"))) {
  const anims = {};
  let frameWidth = 0;
  let frameHeight = 0;
  for (const file of pngs(join(spriteRoot, "monsters", id))) {
    const { width, height } = pngSize(join(spriteRoot, "monsters", id, file));
    const size = height / 4; // four direction rows
    if (!Number.isInteger(size) || width % size !== 0)
      throw new Error(`monster sheet is not a 4-row grid of square frames: ${id}/${file}`);
    frameWidth = frameHeight = size;
    anims[basename(file, ".png")] = {
      file: `sprites/monsters/${id}/${file}`,
      frames: width / size,
    };
  }
  if (Object.keys(anims).length) manifest.monsters[id] = { frameWidth, frameHeight, rows: 4, anims };
}

manifest.skills = pngs(join(spriteRoot, "skills")).map((f) => ({
  id: basename(f, ".png"),
  file: `sprites/skills/${f}`,
}));

const outJson = join(spriteRoot, "..", "manifest.json");
writeFileSync(outJson, JSON.stringify(manifest, null, 2) + "\n");

const generatedDir = join(root, "packages/shared/src/generated");
mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  join(generatedDir, "sprite-ids.ts"),
  `// GENERATED by tools/build-assets.mjs — do not edit by hand.\n` +
    `export const HERO_SPRITE_IDS = ${JSON.stringify(Object.keys(manifest.heroes))} as const;\n` +
    `export const MONSTER_SPRITE_IDS = ${JSON.stringify(Object.keys(manifest.monsters))} as const;\n` +
    `export const SKILL_ICON_IDS = ${JSON.stringify(manifest.skills.map((s) => s.id))} as const;\n` +
    `export type HeroSpriteId = (typeof HERO_SPRITE_IDS)[number];\n` +
    `export type MonsterSpriteId = (typeof MONSTER_SPRITE_IDS)[number];\n` +
    `export type SkillIconId = (typeof SKILL_ICON_IDS)[number];\n`,
);

const heroAnims = Object.values(manifest.heroes).reduce((n, h) => n + Object.keys(h.anims).length, 0);
const monsterAnims = Object.values(manifest.monsters).reduce((n, m) => n + Object.keys(m.anims).length, 0);
console.log(
  `manifest: ${Object.keys(manifest.heroes).length} heroes (${heroAnims} sheets), ` +
    `${Object.keys(manifest.monsters).length} monsters (${monsterAnims} sheets), ` +
    `${manifest.skills.length} skill icons`,
);
